services:
  postgres:
    image: postgres:15-alpine
    container_name: music-streaming-db
    environment:
      POSTGRES_DB: musicdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - music-network

  app:
    build: .
    container_name: music-streaming-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/musicdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - music-network

  locust:
    image: locustio/locust
    container_name: music-streaming-locust
    depends_on:
      - app
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    ports:
      - "8089:8089"
    command: >
      -f /mnt/locust/locustfile.py
      --host http://app:8080
    networks:
      - music-network
      
volumes:
  postgres_data:

networks:
  music-network:
    driver: bridge
